### ISSUE TITLE
some thing about ckpt

### ISSUE THREAD

**Issue by davidfrz** [xyhanHIT/PL-VTON#1]
hello, I am so happy to see this wonderful project, but when I download the checkpoint from the README, it shows I have no right. Could I can access it?

**Comment by xyhanHIT** [comment]
Sorry for the late reply. We have changed the permission and now you can access it. Thank you for following our work!

**Comment by xyhanHIT** [comment]
Sorry for the late reply. We have changed the permission and now you can access it. Thank you for following our work!

2023-03-28 13:34:22"范润泽" ***@***.***>写道：

hello, I am so happy to see this wonderful project, but when I download the checkpoint from the README, it shows I have no right. Could I can access it?
